[package]
name = "verify"
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
div_conquer.workspace = true
fibonacci.workspace = true
kmp.workspace = true
mo.workspace = true
permutation.workspace = true
proconio.workspace = true
ranges.workspace = true
rle.workspace = true
